# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.16.0
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Notebook 4 — Switching oscillator networks on CA1 broadband LFP
#
# Fit `state_space_practice.oscillator_models.DirectedInfluenceModel`
# (DIM) on multi-channel CA1 broadband (non-bandpass-filtered) LFP from
# **`j1620210710_.nwb / 02_r1`**. The model assumes each LFP channel
# is generated by a damped oscillator whose transition dynamics (coupling
# and phase relationships) switch between discrete states:
#
# $$x_t = A_{s_t} x_{t-1} + w_t, \quad w_t \sim N(0, Q)$$
# $$y_t = H x_t + v_t, \quad v_t \sim N(0, R)$$
# $$s_t \sim \text{Categorical}(Z[s_{t-1}, :])$$
#
# where `A_{s_t}` encodes per-state directional coupling between
# oscillators (the "directed influence"). With `edge_l1` regularization,
# the model learns **sparse** coupling graphs — most oscillator pairs
# are uncoupled, and the nonzero couplings reveal which channels
# directly influence each other within each state.
#
# **Science question**: do the discrete states separate ripple events
# from non-ripple background? Does the coupling structure differ
# between the two regimes?
#
# **References**:
# - Hsin, Eden, Stephen (2022). Switching Functional Network Models of
#   Oscillatory Brain Dynamics. Asilomar.
# - Hsin, Eden, Stephen (2024). Switching Models of Oscillatory Networks
#   Greatly Improve Inference of Dynamic Functional Connectivity.

# %% [markdown]
# ## Setup

# %%
from state_space_playground.gpu import pick_free_gpu

pick_free_gpu(min_free_mb=20_000)

# %%
import os
import time

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from state_space_practice.oscillator_models import DirectedInfluenceModel
from state_space_practice.oscillator_regularization import OscillatorPenaltyConfig

from state_space_playground.session import load_session

assert jax.config.jax_enable_x64, "f64 must be enabled"
print(f"jax dtype: {jnp.zeros(1).dtype}, devices: {jax.devices()}")

# %% [markdown]
# ## Configuration

# %%
N_CHANNELS: int = int(os.environ.get("NB4_N_CHANNELS", "4"))
N_DISCRETE_STATES: int = 2
N_SGD_STEPS: int = int(os.environ.get("NB4_N_STEPS", "200"))
WINDOW_SEC: float = float(os.environ.get("NB4_WINDOW_SEC", "60"))
EDGE_L1: float = 0.01  # sparsity penalty on coupling strengths
INIT_FREQ_HZ: float = 8.0  # theta (~8 Hz) — the dominant rhythm during running

print(f"config: N_CHANNELS={N_CHANNELS}, N_DISCRETE_STATES={N_DISCRETE_STATES}, "
      f"N_SGD_STEPS={N_SGD_STEPS}, WINDOW_SEC={WINDOW_SEC}s, "
      f"EDGE_L1={EDGE_L1}, init_freq={INIT_FREQ_HZ} Hz")

# %% [markdown]
# ## Load session and prepare LFP data

# %%
data = load_session("j1620210710_.nwb", "02_r1", use_sorted_hpc=True)

# Use the RAW (non-bandpass-filtered) LFP from LFPOutput, NOT the
# ripple-band filtered version. Despite the misleading key name
# "ripple_lfps", this is the base 1 kHz anti-alias-filtered LFP
# containing the full frequency spectrum up to 500 Hz (Nyquist).
# The oscillator model should learn frequency structure from the data,
# not receive pre-filtered input.
lfp_full = data["ripple_lfps"]
ripple_times = data["ripple_times"]

lfp_dt = float(np.median(np.diff(lfp_full.index.values[:1000])))
lfp_fs = 1.0 / lfp_dt
print(f"Raw LFP (from LFPOutput): {lfp_full.shape[0]:,} samples × "
      f"{lfp_full.shape[1]} channels @ {lfp_fs:.0f} Hz")
print(f"  value range: [{float(lfp_full.values.min()):.0f}, "
      f"{float(lfp_full.values.max()):.0f}] µV")
print(f"Ripple events: {len(ripple_times)}")

# %% [markdown]
# ### Select channels and time window
#
# Pick the N_CHANNELS with the highest variance (most ripple power).
# Select a window centered on a region with several ripple events.

# %%
# Channels by decreasing variance (proxy for ripple power)
channel_vars = lfp_full.var()
channel_order = channel_vars.sort_values(ascending=False).index.tolist()
selected_channels = channel_order[:N_CHANNELS]
print(f"Selected channels (by variance): {selected_channels}")
print(f"  variances: {[f'{channel_vars[c]:.1f}' for c in selected_channels]}")

# Find a time window with high ripple density
# Bin ripple events into 10-second blocks and pick the densest
t_start_session = float(lfp_full.index.min())
t_end_session = float(lfp_full.index.max())
ripple_starts = ripple_times["start_time"].to_numpy()

block_edges = np.arange(t_start_session, t_end_session, 10.0)
ripple_counts, _ = np.histogram(ripple_starts, bins=block_edges)
# Find the densest block that allows a full WINDOW_SEC window around it
safe_mask = (block_edges[:-1] > t_start_session + WINDOW_SEC / 2) & \
            (block_edges[:-1] < t_end_session - WINDOW_SEC / 2)
safe_counts = np.where(safe_mask, ripple_counts, 0)
best_block_idx = int(np.argmax(safe_counts))
t_center = float(block_edges[best_block_idx] + 5.0)  # center of best 10s block
t_win_lo = t_center - WINDOW_SEC / 2
t_win_hi = t_center + WINDOW_SEC / 2

win_mask = (lfp_full.index >= t_win_lo) & (lfp_full.index <= t_win_hi)
lfp_window = lfp_full.loc[win_mask, selected_channels].to_numpy()
time_window = lfp_full.index[win_mask].to_numpy()
n_time = len(time_window)

# Count ripples in the window
ripples_in_win = ripple_times[
    (ripple_times["start_time"] >= t_win_lo) &
    (ripple_times["start_time"] <= t_win_hi)
]
print(f"\nWindow: [{t_win_lo:.1f}, {t_win_hi:.1f}] ({WINDOW_SEC}s)")
print(f"  T = {n_time:,} samples @ {lfp_fs:.0f} Hz")
print(f"  Ripples in window: {len(ripples_in_win)}")
print(f"  LFP shape: {lfp_window.shape}")
print(f"  LFP std per channel: {lfp_window.std(axis=0).tolist()}")

# Standardize each channel to zero-mean unit-variance for numerical stability
lfp_mean = lfp_window.mean(axis=0)
lfp_std = lfp_window.std(axis=0)
lfp_normed = (lfp_window - lfp_mean) / np.maximum(lfp_std, 1e-10)
print("  Standardized: mean≈0, std≈1 per channel")

# %% [markdown]
# ## Initialize and fit DirectedInfluenceModel

# %%
n_osc = N_CHANNELS  # one oscillator per LFP channel
key = jax.random.key(42)

# Initialize oscillator parameters.
# All oscillators start at the same frequency (theta ~8 Hz). SGD will
# adjust per-oscillator frequencies if the data supports it. Theta is
# the dominant rhythm during running behavior; the model should discover
# any frequency switches (e.g., to ripple-band ~200 Hz) via the
# discrete state mechanism.
freqs = jnp.full(n_osc, INIT_FREQ_HZ)
auto_regressive_coef = jnp.full(n_osc, 0.95)  # slowly decaying oscillation
process_variance = jnp.full(n_osc, 0.1)
measurement_variance = 1.0

# Start with zero coupling (let SGD discover the structure)
coupling_strength = jnp.zeros((n_osc, n_osc, N_DISCRETE_STATES))
phase_difference = jnp.zeros((n_osc, n_osc, N_DISCRETE_STATES))

model = DirectedInfluenceModel(
    n_oscillators=n_osc,
    n_discrete_states=N_DISCRETE_STATES,
    sampling_freq=lfp_fs,
    freqs=freqs,
    auto_regressive_coef=auto_regressive_coef,
    process_variance=process_variance,
    measurement_variance=measurement_variance,
    coupling_strength=coupling_strength,
    phase_difference=phase_difference,
)
print(f"DIM: {n_osc} oscillators, {N_DISCRETE_STATES} states, "
      f"{lfp_fs:.0f} Hz, init_freq={INIT_FREQ_HZ} Hz")
print(f"  continuous state dim: {2 * n_osc} per discrete state")

# Regularization: edge_l1 for sparse coupling
penalty_config = OscillatorPenaltyConfig(
    edge_l1=EDGE_L1,
    exclude_diagonal=True,  # don't penalize self-coupling
)
print(f"  regularization: edge_l1={EDGE_L1}")

# %%
print(f"Fitting DIM with {N_SGD_STEPS} SGD steps...")
t0 = time.time()
lls = model.fit_sgd(
    observations=jnp.asarray(lfp_normed),
    key=key,
    num_steps=N_SGD_STEPS,
    verbose=True,
    connectivity_penalty=penalty_config,
)
elapsed = time.time() - t0
n_finite = int(np.sum(np.isfinite(np.asarray(lls))))
print(f"\nDone in {elapsed:.1f}s ({elapsed/N_SGD_STEPS:.2f}s/step)")
print(f"  first LL = {lls[0]:.1f}, last LL = {lls[-1]:.1f}")
print(f"  finite LLs: {n_finite}/{len(lls)}")

# %% [markdown]
# ## Diagnostic plots

# %% [markdown]
# ### SGD convergence

# %%
fig, ax = plt.subplots(figsize=(8, 3.5))
ax.plot(np.asarray(lls), lw=1.2)
ax.set_xlabel("SGD step")
ax.set_ylabel("log-likelihood")
ax.set_title("DIM SGD convergence")
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Smoothed discrete state probabilities vs ripple events
#
# The key plot: do the model's inferred discrete states align with
# independently-detected ripple events?

# %%
disc_probs = np.asarray(model.smoother_discrete_state_prob)  # (n_time, n_states)
print(f"Discrete state probs: shape={disc_probs.shape}")

fig, axes = plt.subplots(3, 1, figsize=(12, 7), sharex=True)

# Panel 1: raw LFP (first channel)
axes[0].plot(time_window, lfp_window[:, 0], lw=0.3, color="k")
axes[0].set_ylabel(f"ch {selected_channels[0]} (µV)")
axes[0].set_title("Raw ripple-band LFP (channel 0)")
# Shade ripple events
for _, row in ripples_in_win.iterrows():
    axes[0].axvspan(row["start_time"], row["end_time"], color="orange", alpha=0.3)
axes[0].set_xlim(time_window[0], time_window[-1])

# Panel 2: discrete state probabilities
for s in range(N_DISCRETE_STATES):
    axes[1].plot(time_window, disc_probs[:, s], lw=0.8, label=f"state {s}")
axes[1].set_ylabel("P(state)")
axes[1].set_title("Smoothed discrete state probabilities")
axes[1].set_ylim(-0.05, 1.05)
axes[1].legend(fontsize=8, loc="upper right")
for _, row in ripples_in_win.iterrows():
    axes[1].axvspan(row["start_time"], row["end_time"], color="orange", alpha=0.2)

# Panel 3: ripple consensus trace if available
if "ripple_consensus_trace" in data:
    rct = data["ripple_consensus_trace"]
    rct_win = rct[(rct.index >= t_win_lo) & (rct.index <= t_win_hi)]
    axes[2].plot(rct_win.index, rct_win.values, lw=0.5, color="C2")
    axes[2].set_ylabel("ripple consensus")
    axes[2].set_title("Ripple consensus trace (from ripple detection)")
    for _, row in ripples_in_win.iterrows():
        axes[2].axvspan(row["start_time"], row["end_time"], color="orange", alpha=0.2)
else:
    axes[2].text(0.5, 0.5, "ripple_consensus_trace not available",
                 transform=axes[2].transAxes, ha="center")

axes[-1].set_xlabel("time (s)")
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Learned coupling matrices per discrete state
#
# Rows = influenced (target), columns = influencing (source).
# Non-zero off-diagonal entries represent directional coupling that
# the model discovered via SGD under the L1 sparsity penalty.

# %%
coupling = np.asarray(model.coupling_strength)  # (n_osc, n_osc, n_states)
print(f"Coupling strength: shape={coupling.shape}")
print(f"  range: [{coupling.min():.4f}, {coupling.max():.4f}]")

fig, axes = plt.subplots(1, N_DISCRETE_STATES, figsize=(4 * N_DISCRETE_STATES, 3.5))
if N_DISCRETE_STATES == 1:
    axes = [axes]
vmax = float(np.abs(coupling).max())
for s in range(N_DISCRETE_STATES):
    im = axes[s].imshow(
        coupling[:, :, s],
        cmap="RdBu_r",
        vmin=-vmax,
        vmax=vmax,
        aspect="equal",
    )
    axes[s].set_title(f"State {s} coupling", fontsize=10)
    axes[s].set_xlabel("source oscillator")
    axes[s].set_ylabel("target oscillator")
    axes[s].set_xticks(range(n_osc))
    axes[s].set_yticks(range(n_osc))
    axes[s].set_xticklabels([str(c) for c in selected_channels], fontsize=8)
    axes[s].set_yticklabels([str(c) for c in selected_channels], fontsize=8)
    plt.colorbar(im, ax=axes[s], shrink=0.8)
fig.suptitle(
    f"Directed coupling (edge_l1={EDGE_L1})",
    y=1.02,
)
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Transition matrix between discrete states

# %%
Z = np.asarray(model.discrete_transition_matrix)
print(f"Discrete transition matrix:\n{Z}")
print(f"  state 0 dwell time: ~{1/(1-Z[0,0]+1e-10):.0f} bins = "
      f"{1/(1-Z[0,0]+1e-10)*lfp_dt*1000:.0f} ms")
print(f"  state 1 dwell time: ~{1/(1-Z[1,1]+1e-10):.0f} bins = "
      f"{1/(1-Z[1,1]+1e-10)*lfp_dt*1000:.0f} ms")

# %% [markdown]
# ### Per-state power spectra (state-conditioned)
#
# For each time bin, weight the power by the posterior state probability
# and average across the session. If the states separate ripple from
# non-ripple, one state should show elevated 150-250 Hz power.

# %%
from scipy.signal import welch  # noqa: E402

# Compute state-conditioned power spectra
fig, axes = plt.subplots(1, N_CHANNELS, figsize=(3.5 * N_CHANNELS, 3.5),
                         sharex=True, sharey=True)
if N_CHANNELS == 1:
    axes = [axes]

# Split the LFP into short segments and assign each segment a state
segment_len = int(0.1 * lfp_fs)  # 100 ms segments
n_segments = n_time // segment_len

for ch_idx in range(N_CHANNELS):
    ch_data = lfp_normed[:n_segments * segment_len, ch_idx]
    segments = ch_data.reshape(n_segments, segment_len)

    # Average state probability per segment
    seg_disc = disc_probs[:n_segments * segment_len].reshape(n_segments, segment_len, -1).mean(axis=1)

    for s in range(N_DISCRETE_STATES):
        weights = seg_disc[:, s]
        # Weighted average of per-segment PSDs
        psds = []
        for seg_i in range(n_segments):
            f, psd = welch(segments[seg_i], fs=lfp_fs, nperseg=min(segment_len, 256))
            psds.append(psd * weights[seg_i])
        avg_psd = np.mean(psds, axis=0) / np.mean(weights)
        axes[ch_idx].semilogy(f, avg_psd, lw=1.2, label=f"state {s}", alpha=0.8)

    axes[ch_idx].set_title(f"ch {selected_channels[ch_idx]}", fontsize=9)
    axes[ch_idx].set_xlabel("freq (Hz)")
    axes[ch_idx].axvspan(150, 250, color="orange", alpha=0.1)
    if ch_idx == 0:
        axes[ch_idx].set_ylabel("PSD (a.u.)")
        axes[ch_idx].legend(fontsize=7)
    axes[ch_idx].grid(True, alpha=0.3)

fig.suptitle("State-conditioned power spectra (orange = ripple band)", y=1.02)
plt.tight_layout()
plt.show()

# %% [markdown]
# ## Summary table

# %%
summary = {
    "n_oscillators": n_osc,
    "n_discrete_states": N_DISCRETE_STATES,
    "n_time_bins": n_time,
    "sampling_freq_Hz": lfp_fs,
    "oscillator_freq_Hz": INIT_FREQ_HZ,
    "edge_l1_penalty": EDGE_L1,
    "sgd_steps": N_SGD_STEPS,
    "final_LL": float(lls[-1]),
    "fit_seconds": elapsed,
    "n_ripples_in_window": len(ripples_in_win),
    "state_0_mean_prob": float(disc_probs[:, 0].mean()),
    "state_1_mean_prob": float(disc_probs[:, 1].mean()),
    "max_coupling_magnitude": float(np.abs(coupling).max()),
}
for k, v in summary.items():
    print(f"  {k}: {v}")

# %% [markdown]
# ## Notes
#
# - **DIM is the most expressive oscillator model** in the hierarchy
#   (COM < CNM < DIM). COM: measurement matrix switches. CNM: process
#   covariance switches. DIM: transition matrix switches (directed
#   coupling). DIM is the right choice for "does functional connectivity
#   change between ripple and non-ripple states?"
#
# - **The `edge_l1` penalty** encourages sparse coupling. Without it,
#   SGD will fill in small nonzero couplings between all pairs. With
#   `edge_l1=0.01`, most couplings should be driven near zero, leaving
#   only the strongest connections visible. Tuning this value is a
#   model-selection question — too high kills all coupling, too low
#   doesn't sparsify.
#
# - **Standardization matters.** The LFP is standardized to zero-mean
#   unit-variance per channel before fitting. Without this, channels
#   with higher variance dominate the likelihood and the oscillator
#   parameters converge to match the highest-power channel only.
#
# - **Time resolution for state switching.** The discrete state
#   transitions happen at the LFP sampling rate (1 kHz). Ripple events
#   last ~70 ms median (70 samples). The model needs enough temporal
#   resolution to capture transitions into and out of ripple states
#   within a single event.
#
# - **Scaling.** 4 channels × 60 seconds × 1 kHz = 60,000 time bins.
#   The switching Kalman filter's scan body runs per bin. At ~200 SGD
#   steps this is ~12M filter evaluations. Runtime depends on n_osc
#   and n_states but should be manageable (~minutes to tens of minutes).
#
# - **What to look for in the plots:**
#   - State probabilities should track ripple events (one state high
#     during orange-shaded periods, the other high otherwise).
#   - Coupling matrices should differ between states (sparse in non-
#     ripple, denser or differently structured during ripple).
#   - State-conditioned PSDs should show elevated 150-250 Hz power
#     in the "ripple state" relative to the "background state."
#
# Next: notebook 5 — switching point process on sorted spikes.
